spring.application.name=main

# Enable the H2 web console
spring.h2.console.enabled=true

# Set the path for the console (optional, default is /h2-console)
spring.h2.console.path=/h2-console

# JDBC URL for H2 (in-memory DB)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2